### ISSUE TITLE
Improve readme (github project settings)

### ISSUE THREAD

**Issue by MeikeSteinhilber** [maehr/zotero-bib-to-gh#54]
Hi,
Thanks a lot for your repo!!!! 🥇 

I have a small improvement. I had to change this setting to make it work in my github project:
![grafik](https://github.com/maehr/zotero-bib-to-gh/assets/78479286/e6f10025-e15e-44a3-a168-1cfc52514ed4)

https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow

Maybe you can add that to the readme file?

**Comment by maehr** [comment]
Thank you, @MeikeSteinhilber, for your comment. I will add this information to the "README" as soon as possible. I guess there is more room for improvement, but I don't have too much time on my hands. I'll see what I can do.
